### ISSUE TITLE
Feature Request: Display all bibliography in a table 

### ISSUE THREAD

**Issue by Peng-YM** [pcubillos/bibmanager#71] opened 2020-09-28 08:27 UTC
First I would like to thank you  for making such an awesome tool. 

When I use bibmanager, I want to have an overview interface for all items in the database. Optionally, it may further allow users to select one (or multiple) items an export them with key-binding or cursor. I think this would make bibmanager easier to use.

**Comment by pcubillos** [comment] 2020-09-30 06:50
Hi, thanks!

I think I get what you are saying. It sounds like a good idea. I'll think about what can be done.
PS: In the meantime ... What I sometime do when I want to browse the database is to run ``bibm edit`` to navigate through the entries (and then close without editing anything).

Thanks for the suggestion!

**Comment by pcubillos** [comment] 2020-10-15 16:25
Hey!
OK, so, it took me some time but I learned how to make full-screen applications, and I think I got something cool working. I put a prototype of the application into this gist file [bm_browser.py](https://gist.github.com/pcubillos/e0b107f47ccd5d3cf73f0e06556a35b1). Can you download it, run it,  play around with it, and give me your opinion?  I tried to make it pretty intuitive to use, so, let me know if that's not the case.

You will need ``prompt_toolkit`` version 3 or above to have it fully working.

**Comment by Peng-YM** [comment] 2020-10-18 09:43
Cool, I am willing to explore this new feature and provide some of my opinions. Thank you very much!

**Comment by Peng-YM** [comment] 2020-10-18 09:47
I think the idea of the current version is very good, but UI can be further improved. I think the [Rich](https://github.com/willmcgugan/rich) lib to display a more intuitive table.

**Comment by pcubillos** [comment] 2020-10-18 20:06
Oh, I didn't know about rich, it has some very nice features, and I like the syntax. Thanks!
But, do you have something specific in mind that could be clearer? is it the content? or how the content is displayed? or the interface itself?
Thanks

**Comment by AaronDavidSchneider** [comment] 2020-10-22 05:48
So as I wrote yesterday in #72: I love `bm_browser.py`! It is indeed a very good addition to `bibmanager` and its very intuiative!

Here are some thoughts:
- maybe use a different key to activate search? slash is for many comouters a combination of two keys
- addtional search that starts searching at the beginning of the word for quicker navigation (e.g. specify the first letter and it jumps to keys that start with this first letter)

Well done! Are you planning on integrating it into `bibmanager`?

**Comment by AaronDavidSchneider** [comment] 2020-10-23 07:13
I forgot: How about a key that lets you open up a paper? (e.g. `o`)

**Comment by pcubillos** [comment] 2020-10-23 07:57
Hey, thanks for the feedback!
I read your mind, already had the opening option working! :)
I'm having troubles displaying the PDF-fetching dialogs, but in principle that should work as well.
And I'll probably throw a go-to-ADS-in-the-browser option too, should be simple to implement.
And yes, I'll incorporate the browser into the main project soon, hopefully before the end of the month because I'm doing some PR at the ADASS meeting.

**Comment by pcubillos** [comment] 2020-10-27 21:11
Hi People,
OK!, I'm finally satisfied with an initial version of the bibmanager browser.  I have no idea how to automate the testing of these interactive routines, but I tried manually all the features and didn't see any odd behavior on linux nor OS X.  I uploaded a pre-release so you can check it out: ``pip install bibmanager==1.3.0rc1``
I'll keep testing over the week and release the official version 1.3 by next week if all looks ok.

I think the browser has a lot of potential to have all the command-line features but in a more GUI-like way, but I purposely left for the future any features that edit the database because that requires a much deeper thinking.

Thanks a lot for the ideas and feedback so far!
(I'll close this issue when releasing v1.3)

**Comment by AaronDavidSchneider** [comment] 2020-10-28 07:15
I can confirm that it works flawlessly on OSX Mojave, anaconda python 3.8

I like the new features!

**Closed** 2020-11-02 09:14 UTC

**Comment by Peng-YM** [comment] 2020-11-02 15:07
Thank you for your excellent job! I will recommend my college members to use bibmanager 👍

**Comment by pcubillos** [comment] 2020-11-02 17:03
Thank you! That's very much appreciated!
